export const shoeCollection = [
  {
    name: "City Strider",
    id: 1,
    description:
      "These low profile sneakers are your perfect casual wear companion. Designed for everyday wear in urban environments. The shoe features a sleek and modern design, with a low-cut silhouette and a durable, yet lightweight build",
    price: "70",
    old_price: "140",
    main_image1: "/images/city-strider.jpg",
    main_image1_thumbnail: "/images/city-strider.jpg",
    main_image2: "/images/city-strider-red.jpg",
    main_image2_thumbnail: "/images/city-strider-red.jpg",
    main_image3: "/images/city-strider-blue.jpg",
    main_image3_thumbnail: "/images/city-strider-blue.jpg",
    main_image4: "/images/city-strider-olive.jpg",
    main_image4_thumbnail: "/images/city-strider-olive.jpg",
  },
  {
    name: "Velocity Surge",
    id: 2,
    description:
      "A high-performance athletic shoe designed for running and other activities, it has a lightweight and breathable upper with durable rubber sole for excellent traction and support.",
    price: "125",
    old_price: "250",
    main_image1: "/images/shoe-velocity-surge.png",
    main_image1_thumbnail: "/images/shoe-velocity-surge.png",
    main_image2: "/images/shoe-velocity-surge-purple.png",
    main_image2_thumbnail: "/images/shoe-velocity-surge-purple.png",
    main_image3: "/images/shoe-velocity-surge-turqoise.png",
    main_image3_thumbnail: "/images/shoe-velocity-surge-turqoise.png",
    main_image4: "/images/shoe-velocity-surge-white.png",
    main_image4_thumbnail: "/images/shoe-velocity-surge-white.png",
  },
  {
    name: "Elevate Pro",
    id: 3,
    description:
      "A high-performance basketball shoe with a durable rubber sole for excellent traction and support, as well as an advanced cushioning system for a comfortable and stable and secure fit. It features reinforced ankle support for added protection during quick cuts and jumps.",
    price: "125",
    old_price: "250",
    main_image1: "/images/shoe-elevate-pro.png",
    main_image1_thumbnail: "/images/shoe-elevate-pro.png",
    main_image2: "/images/shoe-elevate-pro-blue.png",
    main_image2_thumbnail: "/images/shoe-elevate-pro-blue.png",
    main_image3: "/images/shoe-elevate-pro-red.png",
    main_image3_thumbnail: "/images/shoe-elevate-pro-red.png",
    main_image4: "/images/shoe-elevate-pro-white.png",
    main_image4_thumbnail: "/images/shoe-elevate-pro-white.png",
  },
];
