export const shoeCollection = [
  {
    name: "Fall Limited Edition Sneakers",
    id: 1,
    description:
      "These low profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they'll withstand everything the weather can offer.",
    price: "125",
    old_price: "250",
    main_image1: "/images/image-product-1.jpg",
    main_image1_thumbnail: "/images/image-product-1-thumbnail.jpg",
    main_image2: "/images/image-product-2.jpg",
    main_image2_thumbnail: "/images/image-product-2-thumbnail.jpg",
    main_image3: "/images/image-product-3.jpg",
    main_image3_thumbnail: "/images/image-product-3-thumbnail.jpg",
    main_image4: "/images/image-product-4.jpg",
    main_image4_thumbnail: "/images/image-product-4-thumbnail.jpg",
  },
  {
    name: "Velocity Surge",
    id: 2,
    description:
      "a high-performance athletic shoe designed for running and other activities, it has a lightweight and breathable upper with durable rubber sole for excellent traction and support.",
    price: "125",
    old_price: "250",
    main_image1: "/images/shoe-velocity-surge.png",
    main_image1_thumbnail: "/images/shoe-velocity-surge.png",
    main_image2: "/images/shoe-velocity-surge.png",
    main_image2_thumbnail: "/images/shoe-velocity-surge.png",
    main_image3: "/images/shoe-velocity-surge.png",
    main_image3_thumbnail: "/images/shoe-velocity-surge.png",
    main_image4: "/images/shoe-velocity-surge.png",
    main_image4_thumbnail: "/images/shoe-velocity-surge.png",
  },
  {
    name: "Elevate Pro",
    id: 3,
    description:
      "a high-performance basketball shoe with a durable rubber sole for excellent traction and support, as well as an advanced cushioning system for a comfortable and stable and secure fit. It features reinforced ankle support for added protection during quick cuts and jumps.",
    price: "150",
    old_price: "250",
    main_image1: "/images/shoe-elevate-pro.png",
    main_image1_thumbnail: "",
    main_image2: "",
    main_image2_thumbnail: "",
    main_image3: "",
    main_image3_thumbnail: "",
    main_image4: "",
    main_image4_thumbnail: "",
  },
];
